name: Deploy to Market

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node v${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - run: npm install
      - run: npm run lint

  build:
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: npm i -g @vercel/ncc
      - run: npm install --production
      - run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            action.yml
            README.md
            dist/

  deploy:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    needs:
      - test
      - build

    steps:
      - name: Download Bundle
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: /app/bundle

      - name: Upload Bundle to Release ${{ github.ref }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /app/bundle
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
