name: "Setup Secret"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - LICENCE

  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - LICENCE

  workflow_dispatch:

jobs:
  pretest:
    name: Set Secret test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - run: npm install
      - run: npm run lint
      - run: npm run build

      - name: Test Action
        uses: ./
        with:
          name:  LAST_RUN_ID
          value: ${{ github.run_id }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
