name: Test Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/*.yml
      - "*.md"
      - LICENCE

  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/workflows/*.yml
      - "*.md"
      - LICENCE

  workflow_dispatch:

jobs:
  pretest:
    name: Set Secret test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node v${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - run: |
          npm i -g @vercel/ncc
          npm install
      - name: Run linters
        run: npm run lint

      - name: Create Dist
        run: npm run build

      - name: Test Action
        uses: ./
        with:
          name:  LAST_RUN_ID
          value: ${{ github.run_id }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
